yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
] 

yatube/posts/urls.py
# posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Страница со списком постов
    #path('index.html', views.index),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    #path('about/', include('about.urls', namespace='about'))
    path('post/create/', views.post_create, name='post_create'),
]

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import(
    LogoutView,
    LoginView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView)

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',LogoutView.as_view(
        template_name='users/logged_out.html'),
        name='logout'),

    path('signup/', views.SignUp.as_view(), name='signup'),

    path('login/', LoginView.as_view(
        template_name='users/login.html'),
        name='login'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
        name='password_reset_form'),
    
    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='reset_done'),

    path('password_change_form/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change_form'),

] 

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank = True,
        null = True,
        on_delete = models.SET_NULL,
        related_name = 'posts'
    )

    def __str__(self):
        # выводим текст поста 
        return self.text

yatube/posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('group', 'text',)

yatube/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')
        

yatube/about/views.py
from django.shortcuts import render
# views.py
# Импорт класса TemplateView, чтобы унаследоваться от него
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    # В переменной template_name обязательно указывается имя шаблона,
    # на основе которого будет создана возвращаемая страница
    template_name = 'about/author.html'

class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
# posts/views.py
import imp
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from .models import Post, Group, User
from django.contrib.auth import get_user_model
from .forms import PostForm
"Главная страница"

User = get_user_model()

def index(request):
    posts = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    title = 'Последние обновления на сайте'
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)

@login_required
# Страница с группой
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.order_by('-pub_date')[:10]
    title = 'Записи сообщества'
    context = {
        'title': title,
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

@login_required
def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=author)
    posts_count = author.posts.count()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    context = {
        'page_obj' : page_obj,
        'author' : author,
        'posts_count' : posts_count,
    }
    return render(request, template, context)

@login_required
def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post = get_object_or_404(Post, pk=post_id)
    group = post.group
    author = post.author
    context = {
        'author' : author,
        'post' : post,
        'group' : group,
    }
    return render(request, 'posts/post_detail.html', context)

@login_required
def post_create(request):
    """Вью-функция страницы создания публикации"""
    form = PostForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()

        return redirect('posts:profile', username=post.author)

    form = PostForm()

    return render(request, 'posts/create_post.html', {'form': form})

yatube/users/views.py
from django.shortcuts import render
# users/views.py
# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    # Из какого класса взять форму
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    # Имя шаблона, куда будет передана переменная form
    template_name = 'users/signup.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %} 

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Подключен файл со стандартными стилями бустрап -->
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
        Контент не подвезли :(((
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
<p>© 2022 Copyright <span style="color:red">Ya</span>tube by Poh</p>    

yatube/templates/includes/header.html
{% load static %}
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
          <ul class="nav nav-pills">
            <li class="nav-item"> 
              <a class="nav-link {% if request.resolver_match.view_name  == 'about:author' %}active{% endif %}" 
              href="{% url 'about:author' %}">Об авторе</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.view_name  == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}">Технологии</a>
            </li>
            <!-- Проверка: авторизован ли пользователь? -->
            {% if request.user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link {% if request.resolver_match.view_name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link {% if request.resolver_match.view_name  == 'users:password_change_form' %}active{% endif %}"
              href="{% url 'users:password_change_form' %}">Изменить пароль</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link {% if request.resolver_match.view_name  == 'users:logout' %}active{% endif %}"
              href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
            {% else %}
            <li class="nav-item"> 
              <a class="nav-link {% if request.resolver_match.view_name  == 'users:login' %}active{% endif %}"  
              href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link {% if request.resolver_match.view_name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}">Регистрация</a>
            </li>
            {% endif %}

          </ul>
          {# Конец добавленого в спринте #}

        </div>
      </nav>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block content %}
  <body>	   
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Новый пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>---------</option>
                      <option value="1">Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Сохранить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    {% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="../css/bootstrap.min.css">
  <title>Последние обновления на сайте</title>
</head>
  <!-- класс py-3 создает отступы сверху и снизу блока -->
    <div class="container py-3">     
      <h1>{% block title %}{{ title }}{% endblock title %}</h1>
      {% for post in page_obj %}
        <article>
            
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul> 
              <p>{{ post.text }}</p>
              {% if post.group %}   
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        <h3>
          <a href="{% url 'posts:profile' user %}">все посты пользователя</a>
         </h3>
          {% include 'posts/paginator.html' %}
         </article>
            <!-- под последним постом нет линии -->
     </div>  
{% endblock  %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-5">
      <ul>
        <li class="list-group-item d-flex justify-content-between align-item-center">
          Дата публикации:<span> {{ post.pub_date|date:"d E Y" }}</span> 
        </li>
        <li class="list-group-item d-flex justify-content-between align-item-center">
          Пост: <span> {{ post.text|truncatechars:30 }} </span>
        </li>
          <li class="list-group-item d-flex justify-content-between align-item-center">
          Группа: <span> {{ group.title }}</span>
          </li>
        {% if post.group %}
        <li class="list-group-item d-flex justify-content-between align-item-center">
           <a href="{% url 'posts:group_list' post.group.slug %}">
             Все записи группы
           </a>
          </li>
          {% endif %}
          <li class="list-group-item d-flex justify-content-between align-item-center">
          Автор: <span> {{ user.get_full_name }}</span>
          </li>
        <li class="list-group-item d-flex justify-content-between align-item-center">
          Всего постов автора: <span> {{ post.author.posts.count }}</span>
        </li>
      </aside>
      <article class="col-12 cal-md-9">
      </article>
    </div>
    {% endblock %}

yatube/templates/posts/profile.html
<!-- templates/posts/profile.html --> 
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ User.username }}
{% endblock %}

{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ posts_count }} </h3>
    <hr>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ author.get_full_name }}
          
          &nbsp;&nbsp;&nbsp;
          <a href="{% url 'posts:profile' user %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        <li>
          Группа: {{ group.title }}
        </li>
      </ul>
      <p>
        {{ post.text|linebreaks }}
      </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
      &nbsp;&nbsp;&nbsp;
      {% if post.group %}
      {% endif %}
    </article>       
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Редактировать пост</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link active" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/logged_out.html
<!DOCTYPE html> 
{% extends "base.html" %}
  <body>	   
    {% block content %}
    <head>
      <meta name="msapplication-TileColor" content="#da532c">
      <meta name="theme-color" content="#ffffff">
      <link rel="stylesheet" href="../css/bootstrap.min.css">
      <title>До встречи!</title>
    </head>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">Выход</div>
              <div class="card-body"> <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row --> 
      </div>
    </main>
    {% endblock %} 
  </body>
</html>

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}

  <head>
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Войти на сайт</title>
  </head>
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты,
          под которым вы регистрировались
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_reset_form' %}">
            <input type="hidden" name="csrfmiddlewaretoken" value="">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>
              <input type="email" name="email" maxlength="254"
                     class="form-control" required id="id_email">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<head>    
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="../css/bootstrap.min.css">
  <title>Регистрация</title>
</head>
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}